---
# general parameters
seed: 92
test_size: 0.2
# parameters for logistic regression
num_cv: 5
max_dtm_features: 2000
# parameters for small language model finetuning
slm_name: distilbert/distilbert-base-uncased
slm_learning_rate: 3e-5
slm_epochs: 1
# parameters for LLMs
llm_max_tokens: 15
llm_temperature: 0
llm_openai_model: gpt-4o  # gpt-3.5-turbo-0125